# Generated by Django 5.0.6 on 2024-06-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stall',
            table='stall',
        ),
    ]
