# Generated by Django 5.0.6 on 2024-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0002_alter_stall_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='stall_name',
            field=models.CharField(default='null', max_length=55),
        ),
    ]
