# Generated by Django 5.0.6 on 2024-06-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0004_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='stall_location',
            field=models.CharField(default='null', max_length=55),
        ),
    ]
