# Generated by Django 5.0.6 on 2024-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_list', '0005_stall_stall_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='stall_name',
        ),
        migrations.AddField(
            model_name='user',
            name='stall_name',
            field=models.CharField(default='null', max_length=55),
        ),
    ]
